#-------------------------------------------------------------------------------
#
# Rubocop
#
#-------------------------------------------------------------------------------
---
AllCops:
  Exclude:
    - "node_modules/**/*"
    - "modules/**/*"
    - ".vagrant/**/*"
    - ".idea/**/*"
Metrics/BlockLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
